apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # NodePort 포트를 설정
  type: NodePort  # 서비스 타입을 NodePort로 설정
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: heebin00/client:v1.2 # !!!! 버전 바꾸기
          ports:
          - containerPort: 80
      nodeSelector:
        app: client  